mode: daemonset
nameOverride: collector
presets:
  kubeletMetrics:
    enabled: true
  kubernetesAttributes:
    enabled: true
    extractAllPodLabels: true
    extractAllPodAnnotations: true
image:
  tag: "0.86.0"
config:
  receivers:
    jaeger: null
    zipkin: null
    kubeletstats:
      collection_interval: 30s
      metric_groups:
        - node
        - pod
    otlp:
      protocols:
        grpc:
        http:
          cors:
            allowed_origins:
              - http://*
              - https://*
          endpoint: 0.0.0.0:4318
  exporters:
    otlp/refinery:
      endpoint: ${REFINERY_ADDRESS}:4317
      headers:
        x-honeycomb-team: ${HONEYCOMB_API_KEY}
      tls:
        insecure: true

    otlp/metrics:
      endpoint: api.honeycomb.io:443
      headers:
        x-honeycomb-team: ${HONEYCOMB_API_KEY}
        x-honeycomb-dataset: service-metrics

    otlp/logging:
      endpoint: api.honeycomb.io:443
      headers:
        x-honeycomb-team: ${HONEYCOMB_API_KEY}
        x-honeycomb-dataset: service-logs

    otlp/traces-eu:
      endpoint: api.eu1.honeycomb.io:443
      headers:
        x-honeycomb-team: ${HONEYCOMB_API_KEY_EU}

    otlp/metrics-eu:
      endpoint: api.eu1.honeycomb.io:443
      headers:
        x-honeycomb-team: ${HONEYCOMB_API_KEY_EU}
        x-honeycomb-dataset: service-metrics

    otlp/logging-eu:
      endpoint: api.eu1.honeycomb.io:443
      headers:
        x-honeycomb-team: ${HONEYCOMB_API_KEY_EU}
        x-honeycomb-dataset: service-logs

    otlp/aspire:
      endpoint: ${ASPIRE_ADDRESS}:4317
      tls:
        insecure: true

  service:
    pipelines:
      metrics:
        exporters: [otlp/metrics, otlp/metrics-eu, otlp/aspire]
      logs:
        exporters: [otlp/logging, otlp/logging-eu, otlp/aspire]
      traces:
        exporters: [otlp/refinery, otlp/traces-eu, otlp/aspire]
