default:
  replicas: 2

opentelemetry-collector:
  presets:
    kubernetesAttributes:
      enabled: true
  image:
    tag: "0.81.0"
  config:
    receivers:
      otlp:
        protocols:
          grpc:
          http:
            cors:
              allowed_origins:
                - http://*
                - https://*
            endpoint: 0.0.0.0:4318
    service:
      pipelines:
        traces:
          processors: [memory_limiter, batch]
          exporters: [otlp, logging, otlp/honeycomb, spanmetrics]