mode: daemonset
nameOverride: collector
resources:
  limits:
    cpu: 1
    memory: 1Gi
presets:
  # kubeletMetrics:
  #   enabled: true
  kubernetesAttributes:
    enabled: true
image:
  tag: "0.81.0"
config:
  receivers:
    otlp:
      protocols:
        grpc:
        http:
          cors:
            allowed_origins:
              - http://*
              - https://*
          endpoint: 0.0.0.0:4318
  processors:
  exporters:
    otlp/refinery:
      endpoint: ${REFINERY_ADDRESS}:4317
      headers:
        x-honeycomb-team: ${HONEYCOMB_API_KEY}
      tls:
        insecure: true

    otlp/metrics:
      endpoint: api.honeycomb.io:443
      headers:
        x-honeycomb-team: ${HONEYCOMB_API_KEY}
        x-honeycomb-dataset: service-metrics
    # otlp/kubelet_metrics:
    #   endpoint: api.honeycomb.io:443
    #   headers:
    #     x-honeycomb-team: ${HONEYCOMB_API_KEY}
    #     x-honeycomb-dataset: "kubelet-metrics"

    otlp/logging:
      endpoint: api.honeycomb.io:443
      headers:
        x-honeycomb-team: ${HONEYCOMB_API_KEY}
        x-honeycomb-dataset: service-logs

  service:
    pipelines:
      metrics: 
        exporters: [otlp/metrics]
      logs:
        exporters: [otlp/logging]
      traces:
        exporters: [otlp/refinery]
    telemetry:
      metrics: null