mode: daemonset
nameOverride: collector
presets:
  kubeletMetrics:
    enabled: true
  kubernetesAttributes:
    enabled: true
    extractAllPodLabels: true
    extractAllPodAnnotations: true
image:
  repository: "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib"
config:
  receivers:
    jaeger: null
    zipkin: null
    kubeletstats:
      insecure_skip_verify: true
      collection_interval: 30s
      metric_groups:
        - node
        - pod
    otlp:
      protocols:
        grpc:
        http:
          cors:
            allowed_origins:
              - http://*
              - https://*
          endpoint: 0.0.0.0:4318
  exporters:
    otlp/refinery:
      endpoint: ${REFINERY_ADDRESS}:4317
      headers:
        x-honeycomb-team: ${HONEYCOMB_API_KEY}
      tls:
        insecure: true

    otlp/metrics:
      endpoint: api.honeycomb.io:443
      headers:
        x-honeycomb-team: ${HONEYCOMB_API_KEY}
        x-honeycomb-dataset: service-metrics

    otlp/logging:
      endpoint: api.honeycomb.io:443
      headers:
        x-honeycomb-team: ${HONEYCOMB_API_KEY}
        x-honeycomb-dataset: service-logs

  service:
    pipelines:
      metrics:
        exporters: 
          - otlp/metrics
      logs:
        exporters: 
          - otlp/logging
      traces:
        exporters: 
          - otlp/refinery
