default:
  envOverrides:
    - name: "OTEL_COLLECTOR_NAME"
      value: "otel-collector.otel-collector"

components:
  accountingService:
    resources:
      limits:
        memory: 60Mi

opentelemetry-collector:
  enabled: false

jaeger:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false

opensearch:
  enabled: false